# Generated by Django 4.0.2 on 2022-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HS', 'Headset'), ('MC', 'Mic'), ('SB', 'Sound Box'), ('KB', 'Keyboard'), ('MS', 'Mouse'), ('MB', 'Motherboard'), ('HD', 'Hard Drive')], default='HS', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
