# Generated by Django 4.0.2 on 2022-02-25 16:21

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.itemImage),
        ),
    ]
