# Generated by Django 4.0.2 on 2022-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_imagem_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagem',
        ),
    ]
