# Generated by Django 4.0.2 on 2022-02-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_image_item_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagem',
            new_name='image',
        ),
    ]
