# Generated by Django 4.0.2 on 2022-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_imagem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='more_information',
            field=models.TextField(default='S', max_length=1500),
            preserve_default=False,
        ),
    ]
