# Generated by Django 4.0.2 on 2022-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_more_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='S', max_length=1500),
            preserve_default=False,
        ),
    ]
